### ISSUE TITLE
要望: Permalink 実装

### ISSUE THREAD

**Issue by mapconcierge** [svgmap/svgMapLv0.1#33]
各データ(レイヤ)を表示した状態＋表示領域/Zoomレベルを Permalink で共有する機能があると便利です。

**Comment by mapconcierge** [comment]
Permalink 実装と関連してURLの短縮化も重要と思います。
https://github.com/svgmap/svgMapLv0.1/issues/34

**Comment by satakagi** [comment]
- https://www.svgmap.org/wiki/index.php?title=%E8%A7%A3%E8%AA%AC%E6%9B%B8#.E8.A1.A8.E7.A4.BA.E7.AF.84.E5.9B.B2.E3.81.AE.E6.8C.87.E5.AE.9A
- https://www.svgmap.org/wiki/index.php?title=%E8%A7%A3%E8%AA%AC%E6%9B%B8#.E8.A1.A8.E7.A4.BA.E3.83.BB.E9.9D.9E.E8.A1.A8.E7.A4.BA.E3.83.AC.E3.82.A4.E3.83.A4.E3.83.BC.E3.81.AE.E6.8C.87.E5.AE.9A
でパーマリンクが一応作れるのですが、リンクを生成・提示する機能が未実装のままなので、忘れないようにします。

**Comment by satakagi** [comment]
パーマリンク生成機能を実装しました。
https://github.com/svgmap/svgMapLv0.1/commit/55a220a79b31e991e58e59afc0a86f0f776a3f8a
